name: Test

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta-recursive
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            prefix=recursive,type=ref,event=branch
            prefix=recursive,type=ref,event=pr
            prefix=recursive,type=semver,pattern={{version}}
            prefix=recursive,type=semver,pattern={{major}}.{{minor}}
            prefix=recursive,type=semver,pattern={{major}}
            prefix=recursive,type=sha

      - name: Docker meta
        id: meta-forward
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build artifacts
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          target: artifacts
          outputs: "type=local,dest=out/"

      - name: Build and push recursive
        uses: docker/build-push-action@v5
        with:
          context: .
          target: aplr-recursive
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-recursive.outputs.tags }}
          labels: ${{ steps.meta-recursive.outputs.labels }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: aplr-forward
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-forward.outputs.tags }}
          labels: ${{ steps.meta-forward.outputs.labels }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: upload
        with:
          draft: true
          prerelease: true
          tag_name: ${{ github.event.inputs.version }}
          files: out/*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output URL
        run: echo '${{ steps.upload.outputs.url }}'
